-- MySQL Script generated by MySQL Workbench
-- Tue Jan 09 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;


-- Building 테이블
CREATE TABLE IF NOT EXISTS `mydb`.`building` (
  `building_id` INT NOT NULL AUTO_INCREMENT,
  `building_name` VARCHAR(255) NOT NULL,
  `max_floor` INT NOT NULL,
  `description_list` TEXT,
  PRIMARY KEY (`building_id`)
) ENGINE=InnoDB;

-- Room 테이블
CREATE TABLE IF NOT EXISTS `mydb`.`room` (
  `room_id` INT NOT NULL AUTO_INCREMENT,
  `room_name` VARCHAR(255) NOT NULL,
  `floor` INT NOT NULL,
  `building_id` INT NOT NULL,
  PRIMARY KEY (`room_id`),
  CONSTRAINT `fk_room_building`
    FOREIGN KEY (`building_id`)
    REFERENCES `mydb`.`building` (`building_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE=InnoDB;

-- Facility 테이블
CREATE TABLE IF NOT EXISTS `mydb`.`facility` (
  `facility_id` INT NOT NULL AUTO_INCREMENT,
  `facility_name` VARCHAR(255) NOT NULL,
  `facility_type` VARCHAR(45) NOT NULL,  -- 편의점, 은행, 서점 등
  `location` VARCHAR(255) NOT NULL,
  `description` TEXT,
  `company_name` VARCHAR(255),
  `building_id` INT DEFAULT NULL, -- 건물에 속하지 않으면 NULL
  PRIMARY KEY (`facility_id`),
  CONSTRAINT `fk_facility_building`
    FOREIGN KEY (`building_id`)
    REFERENCES `mydb`.`building` (`building_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE
) ENGINE=InnoDB;

-- Food 테이블
CREATE TABLE IF NOT EXISTS `mydb`.`food` (
  `food_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `location` VARCHAR(255) NOT NULL,
  `description` TEXT,
  PRIMARY KEY (`food_id`)
) ENGINE=InnoDB;

-- Cafe 테이블
CREATE TABLE IF NOT EXISTS `mydb`.`cafe` (
  `cafe_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `location` VARCHAR(255) NOT NULL,
  `description` TEXT,
  PRIMARY KEY (`cafe_id`)
) ENGINE=InnoDB;

-- Convenience store 테이블
CREATE TABLE IF NOT EXISTS `mydb`.`convenience_store` (
  `store_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `location` VARCHAR(255) NOT NULL,
  `description` TEXT,
  `company_name` VARCHAR(255),
  PRIMARY KEY (`store_id`)
) ENGINE=InnoDB;

-- Way 테이블 (길 정보)
CREATE TABLE IF NOT EXISTS `mydb`.`way` (
  `way_id` INT NOT NULL AUTO_INCREMENT,
  `way_start` VARCHAR(255) NOT NULL,
  `way_end` VARCHAR(255) NOT NULL,
  `time` INT NOT NULL,   -- 소요시간 (분 단위)
  `stair_number` INT NOT NULL,  -- 계단 수
  `crosswalk_number` INT NOT NULL,  -- 횡단보도 수
  `length` INT NOT NULL,  -- 길이 (미터 단위)
  `has_elevator` BOOLEAN NOT NULL,  -- 엘리베이터 여부
  PRIMARY KEY (`way_id`)
) ENGINE=InnoDB;

-- Route 테이블 (길 찾기 경로)
CREATE TABLE IF NOT EXISTS `mydb`.`route` (
  `route_id` INT NOT NULL AUTO_INCREMENT,
  `route_start` VARCHAR(255) NOT NULL,
  `route_end` VARCHAR(255) NOT NULL,
  `time` INT NOT NULL,  -- 경로의 소요시간
  `stair_number` INT NOT NULL,  -- 경로의 계단 수
  `crosswalk` INT NOT NULL,  -- 경로의 횡단보도 수
  `length` INT NOT NULL,  -- 경로의 길이
  `has_elevator` BOOLEAN NOT NULL,  -- 경로에 엘리베이터 포함 여부
  `type` VARCHAR(50) NOT NULL,  -- 경로 타입 (빠른길, 일반길, 편한길)
  PRIMARY KEY (`route_id`)
) ENGINE=InnoDB;